version: "3.4"

services:
  pan_webapp_front:
    container_name: pan_webapp_front
    restart: always
    build: .
    ports:
      - 4000:3000
    stdin_open: true
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
volumes:
  data: